FROM java
MAINTAINER Daniel Dowd <danny25106@gmail.com>
ENTRYPOINT ["/usr/bin/java", "-jar", "/opt/dukc/eurekaServer/dukc-eureka-server-0.1.0-SNAPSHOT.jar"]

ADD target/dukc-eureka-server-0.1.0-SNAPSHOT.jar /opt/dukc/eurekaServer/dukc-eureka-server-0.1.0-SNAPSHOT.jar