server:
  port: 9200
turbine:
  aggregator:
      clusterConfig: MYCLUSTER
    appConfig: microservice-one,microservice-two,zuul-server
    clusterNameExpression: metadata['cluster']
    combineHostPort: true

eureka:
  hostname: localhost
  password: s3cr3t
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/