FROM java
MAINTAINER Daniel Dowd <danny25106@gmail.com>
ENTRYPOINT ["/usr/bin/java", "-jar", "/opt/dukc/hystrixDashboard/dukc-hystrix-dashboard-0.1.0-SNAPSHOT.jar"]

ADD target/dukc-hystrix-dashboard-0.1.0-SNAPSHOT.jar /opt/dukc/hystrixDashboard/dukc-hystrix-dashboard-0.1.0-SNAPSHOT.jar